/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentaciones;

import dominio.Cuenta;
import dominio.RetiroSinCuenta;
import excepciones.PersistenciaException;
import implementaciones.ClientesDAO;
import interfaces.IClientesDAO;
import interfaces.ICuentasDAO;
import interfaces.IDepositosDAO;
import interfaces.IDireccionesDAO;
import interfaces.IMoviminetosDAO;
import interfaces.IRetirosSinCuentaDAO;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * Frame de retiros sin tarjeta
 *
 * @author julio
 */
public class RetiroForm extends javax.swing.JFrame {

    private static final Logger LOG = Logger.getLogger(ClientesDAO.class.getName());//Logger para errores
    private final IClientesDAO clientesDAO;//Interfaz de clientes
    private final IDireccionesDAO direccionesDAO;//Interfaz de direcciones
    private final ICuentasDAO cuentasDAO;//Interfaz de cuentas
    private final IRetirosSinCuentaDAO retirosDAO;//Interfaz de retiros
    private final IDepositosDAO depositosDAO;//Interfaz de depósitos
    private final IMoviminetosDAO movimientosDAO;//Interfaz de movimientos

    /**
     * Constructor para los retiros, se inicializan las interfaces
     *
     * @param clientesDAO Interfaz de clientes
     * @param direccionesDAO Interfaz de direcciones
     * @param cuentasDAO Interfaz de cuentas
     * @param retirosDAO Interfaz de retiros
     * @param depositosDAO Interfaz de depósitos
     * @param movimientosDAO Interfaz de movimientos
     */
    public RetiroForm(IClientesDAO clientesDAO, IDireccionesDAO direccionesDAO, ICuentasDAO cuentasDAO, IRetirosSinCuentaDAO retirosDAO, IDepositosDAO depositosDAO, IMoviminetosDAO movimientosDAO) {
        this.clientesDAO = clientesDAO;
        this.direccionesDAO = direccionesDAO;
        this.cuentasDAO = cuentasDAO;
        this.retirosDAO = retirosDAO;
        this.depositosDAO = depositosDAO;
        this.movimientosDAO = movimientosDAO;
        initComponents();
        this.setTitle("Retiros sin cuenta");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        txtContrasena = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFolio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(192, 212, 193));

        btnAceptar.setBackground(new java.awt.Color(100, 156, 104));
        btnAceptar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Aceptar");
        btnAceptar.setBorder(null);
        btnAceptar.setBorderPainted(false);
        btnAceptar.setFocusPainted(false);
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAceptarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAceptarMouseReleased(evt);
            }
        });
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(100, 156, 104));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("");
        btnCancelar.setBorder(null);
        btnCancelar.setBorderPainted(false);
        btnCancelar.setFocusPainted(false);
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCancelarMousePressed(evt);
            }
        });
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(55, 81, 55));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Monto");

        txtMonto.setBackground(new java.awt.Color(192, 212, 193));
        txtMonto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMonto.setBorder(null);
        txtMonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMontoKeyTyped(evt);
            }
        });

        txtContrasena.setBackground(new java.awt.Color(192, 212, 193));
        txtContrasena.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtContrasena.setBorder(null);
        txtContrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContrasenaKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(55, 81, 55));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Folio");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(55, 81, 55));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Contraseña");

        txtFolio.setBackground(new java.awt.Color(192, 212, 193));
        txtFolio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtFolio.setBorder(null);
        txtFolio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFolioKeyTyped(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(236, 196, 100));
        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Retiros sin cuenta");
        jLabel4.setOpaque(true);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(0, 0, 0)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método que extrae los datos para el retiro, y válida si estan vacios, si
     * no estan crea un retiro con la información, si ocurre un error se llaman
     * los mensajes.
     *
     * @return Un retiro sin cuenta con los datos obtenidos
     * @throws PersistenciaException Para obtener los errores que puedan suceder
     */
    private RetiroSinCuenta extrarDatosForm() throws PersistenciaException {
        if (txtFolio.getText().isEmpty() || txtContrasena.getText().isEmpty() || txtMonto.getText().isEmpty()) {
            this.mostrarMensajeErrorDatos();
            throw new PersistenciaException("");
        } else {
            Integer folio = Integer.parseInt(txtFolio.getText());
            Integer contrasena = Integer.parseInt(txtContrasena.getText());
            Float monto = Float.valueOf(txtMonto.getText());
            RetiroSinCuenta retiroSinCuenta = new RetiroSinCuenta(folio, contrasena, monto);
            return retiroSinCuenta;

        }

    }

    /**
     * Mensaje de error para cuando el folio no es correcto.
     */
    public void mostrarMensajeErrorConsultarCuenta() {
        JOptionPane.showMessageDialog(this, "El folio no es correcto",
                "Error", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * Mensaje de error para cuando hay espacios vacíos en el formulario.
     */
    public void mostrarMensajeErrorDatos() {
        JOptionPane.showMessageDialog(this, "Todos los datos deben de estar llenos",
                "Error", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * Mensaje de error para cuando el saldo en la cuenta es insuficiente.
     */
    public void mostrarMensajeErrorSaldoInsuficiente() {
        JOptionPane.showMessageDialog(this, "Saldo en cuenta insucificiente",
                "Error", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * Mensaje de error para cuando la contraseña dada es incorrecta.
     */
    public void mostrarMensajeErrorContrasena() {
        JOptionPane.showMessageDialog(this, "La Contraseña no es correcta",
                "Error", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * Mensaje de error para cuando el folio ya fue cobrado o se venció el
     * tiempo.
     */
    public void mostrarMensajeErrorEstado() {
        JOptionPane.showMessageDialog(this, "Este folio ya fue cobrado o el tiempo vencio",
                "Error", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * Mensaje informativo que avisa cuando el retiro ya se realizo.
     */
    public void mostrarMensajeRealizado() {
        JOptionPane.showMessageDialog(this, "Retiro realizado",
                "Informacion", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * Método que limpia los campos de texto.
     */
    public void limpiarDatos() {
        this.txtFolio.setText("");
        this.txtContrasena.setText("");
        this.txtMonto.setText("");
    }

    /**
     * Método que consulta un retiro a partir del folio para comprobar que
     * existe.
     */
    private void comprobarFolio() {
        try {
            RetiroSinCuenta retiroSinCuenta = this.extrarDatosForm();
            this.retirosDAO.consultar(retiroSinCuenta.getFolio());
        } catch (PersistenciaException ex) {
            LOG.log(Level.SEVERE, ex.getMessage());
            this.mostrarMensajeErrorConsultarCuenta();
        }
    }

    /**
     * Método que comprueba si hay saldo disponible, se almacenan los datos y se
     * comparan.
     *
     * @return El folio consultado
     */
    private RetiroSinCuenta comprobarSaldo() {
        try {
            RetiroSinCuenta retiroSinCuenta = this.extrarDatosForm();
            RetiroSinCuenta folioConsultado = this.retirosDAO.consultar(retiroSinCuenta.getFolio());
            Cuenta consultarCuenta = this.cuentasDAO.consultarCuenta(folioConsultado.getCuenta_retirada());

            if (consultarCuenta.getMonto() < retiroSinCuenta.getMonto()) {
                this.mostrarMensajeErrorSaldoInsuficiente();
                return null;
            } else {
                return folioConsultado;
            }
        } catch (PersistenciaException ex) {
            LOG.log(Level.SEVERE, ex.getMessage());
            return null;
        }
    }

    /**
     * Método que comprueba si todavia es posible el retiro a traves de
     * validaciones y consultas.
     *
     * @param retiroSinCuenta Es el retiro del cual se prueba
     * @return Booleano para comprobar el estado
     */
    private boolean comprobarEstadoTiempo(RetiroSinCuenta retiroSinCuenta) {
        try {
            this.retirosDAO.comprobarEstado(retiroSinCuenta.getFolio());
            RetiroSinCuenta estado = this.retirosDAO.consultar(retiroSinCuenta.getFolio());
            return estado.getEstado().equals("Pendiente");
        } catch (PersistenciaException ex) {
            LOG.log(Level.SEVERE, ex.getMessage());
            return false;
        }
    }

    /**
     * Método que engloba los proceos para realizar el retiro, valida los datos
     * y muestra mensajes de error en caso de necesitarse.
     */
    private void realizarRetiro() {
        try {
            RetiroSinCuenta retiroSinCuenta = this.extrarDatosForm();
            this.comprobarFolio();
            RetiroSinCuenta datosComprobados = this.comprobarSaldo();
            if (datosComprobados == null) {
            } else {
                if (retiroSinCuenta.getContraseña().equals(datosComprobados.getContraseña())) {
                    if (this.comprobarEstadoTiempo(retiroSinCuenta)) {
                        this.retirosDAO.actualizarRetiro(datosComprobados.getFolio(), datosComprobados.getCuenta_retirada(), retiroSinCuenta.getMonto());
                        this.mostrarMensajeRealizado();
                        this.limpiarDatos();
                    } else {
                        this.mostrarMensajeErrorEstado();
                    }
                } else {
                    this.mostrarMensajeErrorContrasena();
                }
            }
        } catch (PersistenciaException ex) {
            LOG.log(Level.SEVERE, ex.getMessage());
        }

    }

    /**
     * Método que se acciona al dar click al botón para volver a la ventana
     * principal.
     *
     * @param evt Evento que se crea al dar click al botón
     */
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        new InicioForm(clientesDAO, direccionesDAO, cuentasDAO, retirosDAO, depositosDAO, movimientosDAO).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * Método que se acciona al dar click al botón para realizar el retiro
     * llamando el método de realizarRetiro.
     *
     * @param evt Evento que se crea al dar click al botón
     */
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        this.realizarRetiro();
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * Evento que restringe los caracteres para la contraseña, permitiendo solo
     * numeros.
     *
     * @param evt Evento que se crea al teclear algo encima
     */
    private void txtContrasenaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContrasenaKeyTyped
        char car = evt.getKeyChar();
        if (car < '0' || car > '9')
            evt.consume();
    }//GEN-LAST:event_txtContrasenaKeyTyped

    /**
     * Evento que restringe los caracteres para el folio, permitiendo solo
     * numeros.
     *
     * @param evt Evento que se crea al teclear algo encima
     */
    private void txtFolioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFolioKeyTyped
        char car = evt.getKeyChar();
        if (car < '0' || car > '9')
            evt.consume();
    }//GEN-LAST:event_txtFolioKeyTyped

    /**
     * Evento que restringe los caracteres para el monto, permitiendo solo
     * numeros, comas y puntos.
     *
     * @param evt Evento que se crea al teclear algo encima
     */
    private void txtMontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoKeyTyped
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9') && (car < ',' || car > '.'))
            evt.consume();
    }//GEN-LAST:event_txtMontoKeyTyped

    /**
     * Evento que se acciona cuando se presiona el botón de aceptar para cambiar
     * de color.
     *
     * @param evt Evento que se crea al dar click al botón
     */
    private void btnAceptarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMousePressed
        this.btnAceptar.setContentAreaFilled(false);
        this.btnAceptar.setOpaque(true);
        this.btnAceptar.setBackground(new Color(148, 116, 69));
    }//GEN-LAST:event_btnAceptarMousePressed

    /**
     * Evento que se acciona cuando se presiona el botón de cancelar para
     * cambiar de color.
     *
     * @param evt Evento que se crea al dar click al botón
     */
    private void btnCancelarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMousePressed
        this.btnCancelar.setContentAreaFilled(false);
        this.btnCancelar.setOpaque(true);
        this.btnCancelar.setBackground(new Color(148, 116, 69));
    }//GEN-LAST:event_btnCancelarMousePressed

    /**
     * Evento que se acciona cuando se suelta el botón para regresar de color.
     *
     * @param evt Evento que se crea al dar click al botón
     */
    private void btnAceptarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseReleased
        this.btnAceptar.setBackground(new Color(100, 156, 104));
    }//GEN-LAST:event_btnAceptarMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtFolio;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
